"""
Collects putative viral genome (*.fna) files generated by a virus
identification tool and move them into a dedicated output directory.
"""

import re
import shutil
from pathlib import Path
import pandas as pd

from phantom.config.loader import ConfigLoader


class GenomeCollector:
    def __init__(self, config: dict, meta_manager):
        self.config = config
        self.tools_map = self.config.get("tools", {})
        self.base_dest = ConfigLoader.resolve_data_path(self.config["genomes"]["path"])
        self.meta_manager = meta_manager

    def _is_valid_format(self, folder_name: str, tool_abbr: str) -> bool:
        pattern = rf"^S\d+_{re.escape(tool_abbr)}$"
        return bool(re.match(pattern, folder_name))

    def scan_for_invalid(self) -> int:
        invalid_count = 0
        for tool_abbr, tool_name in self.tools_map.items():
            tool_config = self.config.get(tool_name)
            if not tool_config:
                continue
            root = ConfigLoader.resolve_data_path(tool_config["path"])
            for file in root.rglob(tool_config["viral_fna"]):
                parts = file.relative_to(root).parts
                subfolder = parts[0] if len(parts) > 1 else "root"
                if not self._is_valid_format(subfolder, tool_abbr):
                    invalid_count += 1
        return invalid_count

    def collect(self, auto_format: bool = False) -> pd.DataFrame:
        """
        Collects files and returns a wide-format DataFrame joined on sample ID.
        """
        all_samples = {}
        for tool_abbr, tool_name in self.tools_map.items():
            tool_config = self.config.get(tool_name)
            if not tool_config: 
                continue
            root = ConfigLoader.resolve_data_path(tool_config["path"])
            dest_dir = self.base_dest / tool_name
            dest_dir.mkdir(parents=True, exist_ok=True)
            sample_counter = 1
            for file in root.rglob(tool_config["viral_fna"]):
                parts = file.relative_to(root).parts
                subfolder = parts[0] if len(parts) > 1 else "root"
                valid = self._is_valid_format(subfolder, tool_abbr)
                if valid:
                    sample_id = subfolder.split("_")[0]
                    formatted_name = f"{subfolder}.fna"
                else:
                    if not auto_format: 
                        continue
                    sample_id = f"S{sample_counter}"
                    formatted_name = f"{sample_id}_{tool_abbr}.fna"
                    sample_counter += 1
                dst_file = dest_dir / formatted_name
                shutil.copy2(file, dst_file)
                if sample_id not in all_samples:
                    all_samples[sample_id] = {"id": sample_id}
                sample = all_samples[sample_id]
                sample[f"{tool_abbr}_original_file"] = file.name
                sample[f"{tool_abbr}_formatted_file"] = formatted_name
        return pd.DataFrame(list(all_samples.values()))
    